pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                dir('CodeAlpha_JavaApplication_UsingGradle') {
                    sh './gradlew assemble'
                }
            }
        }

        stage('Test') {
            steps {
                dir('CodeAlpha_JavaApplication_UsingGradle') {
                    sh './gradlew test'
                }
            }
        }
    }
}

// Jenkins CI pipeline